services:
  rtsp-to-onvif:
    image: kulasolutions/rtsp-to-onvif:latest
    hostname: rtsp-to-onvif
    volumes:
      - ./config.yaml:/onvif.yaml
    network_mode: "host"   
    cap_add:
      - NET_ADMIN
    #environment:
    #  DEBUG: 1